[package]
name = "acc_fmics"
version.workspace = true
edition.workspace = true

[dependencies]
grust = { workspace = true }
priority_stream = { workspace = true }
timer_stream = { workspace = true }
tokio = { workspace = true }
futures = { workspace = true }
