image: rust:1.76-slim

variables:
  GIT_SUBMODULE_STRATEGY: recursive

# to remove when no dependency to protoc
before_script:
  - apt-get update && apt-get install -y protobuf-compiler curl

stages:
  - build
  - test
  - deploy

build-job:
  stage: build
  script:
    - echo "Compiling the code..."
    - cargo build
    - echo "Compile complete."

unit-test-job:
  stage: test
  script:
    - echo "Running unit tests..."
    - cargo test --all
    - cargo test --doc
    - echo "Tests passed."

lint-test-job:
  stage: test
  script:
    - echo "Running linter..."
    - cargo clippy -- -D warnings
    - echo "No lint issues found."

pages:
  stage: deploy
  only:
    - main
    - website-setup
  script:
    - echo "Deploying documentation..."
    - cargo doc --no-deps
    - echo "Documentation successfully deployed."
  artifacts:
    paths:
      - target/doc/grust

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
