[package]
name = "grustine"
version = "0.1.0"
edition = "2021"
authors = ["Émilie THOMÉ <emilie.e.thome@renault.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
lalrpop = "0.19.10"

[dependencies]
lalrpop-util = {version = "0.19.10", features = ["lexer"]}
codespan-reporting = "0.11.1"
strum = { version = "0.21", features = ["derive"] }
once_cell = "1.18.0"
syn = { version = "2.0.33", features = ["extra-traits"] }
prettyplease = "0.2.15"
serde = { version = "1.0", features = ["derive"] }
itertools = "0.11.0"
proc-macro2 = "1.0.78"
quote = "1.0.35"
petgraph = { version = "0.6.4", features = ["serde-1"] }

[dev-dependencies]
insta = { version = "1.34.0", features = ["yaml"] }

[profile.dev.package]
insta.opt-level = 3
similar.opt-level = 3
