[workspace]
resolver = "2"
exclude = ["creusot"]
members = [
    "proc",
    "grust",
    "compiler",
    "greact",
    "examples/*",
    "compiler_ast",
    "compiler_common",
    "compiler_lir",
    "priority_stream",
    "timer_stream",
    "json",
    "grust_std",
]
