[workspace]
resolver = "2"
exclude = ["creusot"]
members = [
    "proc",
    "grust",
    "greact",
    "examples/*",
    "compiler_common",
    "compiler_ir0",
    "compiler_ir1",
    "compiler_ir2",
    "compiler_top",
    "priority_stream",
    "timer_stream",
    "json",
    "grust_std",
]
