[package]
name = "compiler_ir1"
version.workspace = true
edition.workspace = true

[features]
no_diagnostics = []

[dependencies]
compiler_common = { workspace = true }
compiler_ir0 = { workspace = true }
