[package]
name = "compiler_top"
version = "0.1.0"
edition = "2021"

[dependencies]
compiler_common = { path = "../compiler_common" }
compiler_ir0 = { path = "../compiler_ir0" }
compiler_ir1 = { path = "../compiler_ir1" }
compiler_ir2 = { path = "../compiler_ir2" }
