[package]
name = "compiler_top"
version.workspace = true
edition.workspace = true

[features]
default = []
diagnostics = []

[dependencies]
compiler_common = {workspace = true}
compiler_ir0 = {workspace = true}
compiler_ir1 = {workspace = true}
compiler_ir2 = {workspace = true}
