function factorial(n: int) -> int {
    let res: int = if n <= 1 then 1 else n * factorial(n-1);
    return res;
}

function fibonacci(n: int) -> int {
    let res: int = if n <= 0 then 0 else (
        if n <= 1 then 1 else fibonacci(n-1) + fibonacci(n-2)
    );
    return res;
}

component lidar_detection(rgb_images: [int; 10]) {
    out regions_of_interest: int = rgb_images.fold(0, |acc: int, n: int| acc + factorial(n));
    out list_of_detections: [int; 10] = rgb_images.map(fibonacci);
}