[package]
name = "timer_stream"
version = "0.1.0"
edition = "2021"

[dependencies]
array-init = "2.1.0"
pin-project = "1.1.5"
rand = "0.8.5"
tokio = { version = "1.38.0", features = [ "macros", "rt", "time", "sync" ] }
futures = "0.3.30"
