enum Priority {
    Low, Medium, High
}

struct Alarm {
    priority: Priority,
    raised: bool,
}

function high_priority(alarm: Alarm) -> bool {
    let is_raiseable: bool = match (alarm) {
        Alarm {
            priority: Priority.High,
            raised: raised,
        } => raised,
        _ => false,
    };
    return is_raiseable;
}

function alarms_processing(alarms: [Alarm; 10]) -> [bool; 10] {
    return alarms.map(high_priority);
}

node alarm_manager(alarms: [Alarm; 10]) {
    out raise: [bool; 10] = alarms_processing(alarms);
}
