enum Priority {
    Low, Medium, High
}

struct Alarm {
    priority: Priority,
    raised: bool,
}

function high_priority(alarm: Alarm) -> bool {
    let is_raiseable: bool = match (alarm) {
        Alarm {
            priority: Priority.High,
            raised: raised,
        } => raised,
        _ => false,
    };
    return is_raiseable;
}

node alarm_manager(alarms: Alarm) {
    out raise: [bool; 10] = alarms.map(high_priority);
}
