[package]
name = "grust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
proc = { path = "../proc" }
grust_std = { path = "../grust_std" }
grust_core = { path = "../grust_core" }
