[package]
name = "compiler_ir0"
version.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
diagnostics = []

[dependencies]
compiler_common = { workspace = true }
