[package]
name = "priority_stream"
version = "0.1.0"
edition = "2021"

[dependencies]
colored = "2.1.0"
pin-project = "1.1.5"
tokio = { version = "1.38.0", features = [ "macros", "rt", "time" ] }
tokio-stream = "0.1.15"
