[package]
name = "priority_stream"
version.workspace = true
edition.workspace = true

[dependencies]
array-init = { workspace = true }
pin-project = { workspace = true }
tokio = { workspace = true }
futures = { workspace = true }
