[package]
name = "priority_stream"
version.workspace = true
edition.workspace = true

[dependencies]
pin-project = { workspace = true }
futures = { workspace = true }

[dev-dependencies]
tokio = { workspace = true }
