[package]
name = "speed_limiter_events"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
grust = { path = "../../grust" }
tokio = "1.37.0"
futures = "0.3.30"
