enum Priority {
    Low, Medium, High
}

struct Alarm {
    priority: Priority,
    raised: bool,
}

function high_priority(alarm_frequence: (Alarm, int)) -> bool {
    let alarm: Alarm = alarm_frequence.0;
    let frequence: int = alarm_frequence.1;
    let is_raiseable: bool = frequence > 3 && match (alarm) {
        Alarm {
            priority: Priority::High,
            raised: raised,
        } => raised,
        _ => false,
    };
    return is_raiseable;
}

node alarm_manager(alarms: [Alarm; 10], frequences: [int; 10]) {
    combined: [(Alarm, int); 10] = zip(alarms, frequences);
    out raise: [bool; 10] = combined.map(high_priority);
}
